.TH MCEXPLORE "1" 2022-05-08 "\ \&" "\ \&"
.SH NAME
mcexplore
.SH SYNOPSIS
.B mcexplore
[-c COMMAND] [-d DIMENSION] [-p PATH] [-r] [-x XORIGIN] [-z ZORIGIN] [-q] [-v] [-V] [-h] xsize [zsize]
.SH DESCRIPTION
Use a minecraft server jar to generate a rectangular section of the world.
.SH OPTIONS
.TP
\fBxsize\fR
The size to generate in the x direction. Measured in chunks (16x16 blocks) by
default (but see the \-r option, below). Must be greater than 25 chunks.

.TP
\fBzsize\fR
The size to generate in the z direction. Measured in chunks (16x16 blocks) by
default (but see the \-r option, below). Must be greater than 25 chunks.
Defaults to the value provided for 'xsize'.

.TP
\fB\-c\fR \fI\,COMMAND\/\fR, \fB\-\-command\fR \fI\,COMMAND\/\fR
The command used to start the server. Defaults to 'java \-jar
minecraft_server.jar nogui'.

.TP
\fB\-d\fR \fI\,DIMENSION\/\fR, \fB\-\-dimension\fR \fI\,DIMENSION\/\fR
The ID and region folder of the dimension to generate. Relative folder paths
are interpreted relative to '\-\-path'. Defaults to
'minecraft:overworld=world/region'.

.TP
\fB\-p\fR \fI\,PATH\/\fR, \fB\-\-path\fR \fI\,PATH\/\fR
The working directory to use when running the server. Defaults to the current
directory (.).

.TP
\fB\-r\fR, \fB\-\-regions\fR
Use units of regions (32x32 chunks) instead of chunks for 'xsize' and 'zsize'.

.TP
\fB\-x\fR \fI\,XORIGIN\/\fR
The X offset to generate land around. Defaults to the server spawn point.

.TP
\fB\-z\fR \fI\,ZORIGIN\/\fR
The Z offset to generate land around. Defaults to the server spawn point.

.TP
\fB\-q\fR, \fB\-\-quiet\fR
Suppress minecraft server output. This is the default behavior.

.TP
\fB\-v\fR, \fB\-\-verbose\fR
Show minecraft server output.

.TP
\fB\-V\fR, \fB\-\-version\fR
Show version number and exit.

.SH AUTHORS
.B mcexplore
was written by DMBuce <https://github.com/DMBuce> and similardilemma <https://github.com/similardilemma>.
.SH DISTRIBUTION
The latest version of mcexplore may be downloaded from
.UR https://github.com/dmbuce/mcexplore
.UE
