#!/bin/bash
# update version every commit

version="2.$(git rev-list --count HEAD).g$(git rev-parse --short HEAD)+1"
echo "Updating version to $version"
sed -i "/version =/ s/=.*/= f'{prog} $version'/" mcexplore.py

