Use a Minecraft server to generate a square of land.

Overview
--------
mcexplore uses a Minecraft server to generate a square land of a specified
size, measured in chunks (16x16 blocks) or regions (32x32 chunks).

Requirements
------------
This script requires Python and https://github.com/twoolie/NBT[Twoolie's NBT
library].

Install
-------

On Arch Linux, you can use the AUR to download, build, and install the
https://aur.archlinux.org/packages/?O=0&K=mcexplore[mcexplore]
package in the usual way.
You will also need to do the same for its dependency, the
https://aur.archlinux.org/packages/python-nbt/[python-nbt] package.

On other distributions, search your package manager for `python nbt`.
If a package for Twoolie's NBT library is available, install it.
Then, download mcexplore.py and make it executable.

On distros that don't have a package for Twoolie's NBT library,
you should be able to create a python virtualenv,
use pip to install the python nbt module into it,
then download and install mcexplore. To do that,
start by downloading and installing virtualenv through your package manager.
Typically the package is called `python-virtualenv` or `python3-virtualenv`.

Then, create a new python virtualenv

 virtualenv -p python3 ~/venv/python3

Install the nbt module

 ~/venv/python3/bin/pip install nbt

Download mcexplore and make it executable

 wget https://raw.githubusercontent.com/DMBuce/mcexplore/master/mcexplore.py
 chmod +x mcexplore.py

Update the shebang in the script so that it uses the python interpreter in the
virtualenv.

 sed -i "1s,^#\!.*,#\!$HOME/venv/python3/bin/python," mcexplore.py

You can, of course, move the script somewhere inside your PATH if you prefer
not to have to type the full path when calling it.

Usage
-----

Always take a backup before running mcexplore against your world.

Before running mcexplore, make sure that the minecraft server isn't running
and that the server directory contains valid files for `server.properties`,
`world/level.dat`, `eula.txt`, and the server jar.

If mcexplore is in your PATH, your server jar is named `minecraft_server.jar`,
and you want to pregenerate 63x63 chunks (1008x1008 blocks) centered on spawn,
you can run

 mcexplore 63

To generate the land centered on (0, 0) instead of spawn,

 mcexplore -x 0 -z 0 63

To do the same in a more verbose way,

 /path/to/mcexplore -v -p /path/to/server -c "java -jar minecraft_server.jar nogui" -x 0 -z 0 63 63

Documentation
-------------

The manual page for mcexplore is kept in AsciiDoc format in mcexplore.1.txt.
You can view it in a text editor, with `make doc; man ./mcexplore.1`, or at 
https://dmbuce.github.io/mcexplore/mcexplore.1.html .

Project documentation can be found in these files:

* LICENSE - Terms and conditions
* README  - This document

The changelog can be viewed by running `git tag -l -n100` in the git
repository.

/////
vim: set syntax=asciidoc ts=4 sw=4 noet:
/////
